return {
  ["Books"] = " ",
  ["Opera"] = " ",
  ["Finder"] = "󰀶 ",
  ["Safari"] = "󰀹 ",
  ["Unknown"] = "󰘔 ",
  ["Preview"] = " ",
  ["Discord"] = "󰙯 ",
  ["Firefox"] = "󰈹 ",
  ["Telegram"] = " ",
  ["Messages"] = "󰍡 ",
  ["Obsidian"] = "󰮊 ",
  ["Calendar"] = " ",
  ["Alacritty"] = " ",
  ["Bitwarden"] = " ",
  ["Battle.net"] = "󰝨 ",
  ["Raindrop.io"] = "󰅟 ",
  ["Hammerspoon"] = "󰣪 ",
  ["Tor Browser"] = " ",
  ["Google Drive"] = " ",
  ["Google Chrome"] = "󰊯 ",
  ["Brave Browser"] = "󱢼 ",
  ["System Settings"] = " ",
  ["Activity Monitor"] = "󰄪 ",
}
